#!/bin/sh

echo "===================="
echo "CERNLIB installation"
echo "===================="

# Define the cern root directory

export CERN=$PWD

# Get the original cernlib sources + corrections

echo "installing cernlib sources"

./Install_cernlib_src


# Define the cernlib version

export CERN_LEVEL=`gunzip -c src_Imakefile.tar.gz | tar tf - | awk -F/ '{print $1}'`

# Get the architecture and the gnu compiler version

ARCH=`uname -m`
export ARCH
./DetermineFC.sh

echo "======================================"
echo "Configuration summary"
echo "---------------------"
echo "Architecture is: "$ARCH
echo "Fortran compiler used: "$FC
echo "CERN_LEVEL is: "$CERN_LEVEL
echo "======================================"


# Fix the cernlib script (BLAS-3 and LAPACK-3 provided by the system)

cp -a $CERN/cernlib.fixed $CERN/$CERN_LEVEL/src/scripts/cernlib


# Install the cernlib libraries

echo "installing cernlib libraries"

./Install_cernlib_lib


# Test the cernlib libraries

echo "testing cernlib libraries"

./Install_cernlib_test


# Install the executables

echo "installing cernlib executables"

./Install_cernlib_bin


# Install the old patchy 4 executables

echo "installing the old patchy 4 executables"

./Install_old_patchy4


# Install the patchy 5 executables

echo "installing the patchy 5 executables"

./Install_cernlib_patchy


# Install cernlib "includes"

echo "installing cernlib includes"

./Install_cernlib_include


echo "fixing known installation problems"

./Install_cernlib_fixes


# All done

echo "Complete cernlib installation finished"
echo "Check the log files in the build/log directory"

